openapi: 3.0.0
info:
  version: 1.0.0
  title: IFAM API
  description: Specification for IFAM's smartlock API
  contact:
    name: IFAM SEGURIDAD SL
    url: http://www.ifam.es/
paths:
  /api/device/pairable:
    $ref: paths/device/api_device_pairable.yaml
  /api/device/pair/encrypted:
    $ref: paths/device/api_device_pair_encrypted.yaml
  /api/device/user/encrypted:
    $ref: paths/device/api_device_user_encrypted.yaml
  /api/device/{device_id}:
    $ref: paths/device/api_device_{device_id}.yaml
  /api/device/{device_id}/encrypted:
    $ref: paths/device/api_device_{device_id}_encrypted.yaml
  /api/device/key/{device_id}/encrypted:
    $ref: paths/device/api_device_key_{device_id}_encrypted.yaml
  /api/device/other-key/{device_id}:
    $ref: paths/device/api_device_other-key_{device_id}.yaml
  /api/device/missing-key/{device_id}:
    $ref: paths/device/api_device_missing-key_{device_id}.yaml
  /api/device/:
    $ref: paths/device/api_device_.yaml
  /api/device/encrypted:
    $ref: paths/device/api_device_encrypted.yaml
  /api/device/mac:
    $ref: paths/device/api_device_mac.yaml
  /api/device/counter:
    $ref: paths/device/api_device_counter.yaml
  /api/device/keys-check:
    $ref: paths/device/api_device_keys-check.yaml
  /api/event/{device_id}:
    $ref: paths/event/api_event_{device-id}.yml
  /api/event:
    $ref: paths/event/event.yml
