openapi: 3.0.0
info:
  version: 1.0.0
  title: IFAM API
  description: Specification for IFAM's smartlock API
  contact:
    name: IFAM SEGURIDAD SL
    url: http://www.ifam.es/
paths:
  /api/device/pairable:
    $ref: paths/api_device_pairable.yaml
  /api/device/pair/encrypted:
    $ref: paths/api_device_pair_encrypted.yaml
  /api/device/user/encrypted:
    $ref: paths/api_device_user_encrypted.yaml
  /api/device/{device_id}:
    $ref: paths/api_device_{device_id}.yaml
  /api/device/{device_id}/encrypted:
    $ref: paths/api_device_{device_id}_encrypted.yaml
  /api/device/key/{device_id}/encrypted:
    $ref: paths/api_device_key_{device_id}_encrypted.yaml
  /api/device/other-key/{device_id}:
    $ref: paths/api_device_other-key_{device_id}.yaml
  /api/device/missing-key/{device_id}:
    $ref: paths/api_device_missing-key_{device_id}.yaml
  /api/device:
    $ref: paths/api_device.yaml
  /api/device/encrypted:
    $ref: paths/api_device_encrypted.yaml
  /api/device/mac:
    $ref: paths/api_device_mac.yaml
  /api/device/counter:
    $ref: paths/api_device_counter.yaml
  /api/device/keys-check:
    $ref: paths/api_device_keys-check.yaml
  /api/event/{device_id}:
    $ref: paths/api_event_{device_id}.yaml
  /api/event:
    $ref: paths/api_event.yaml
  /api/gateway/by_mac/{gateway_mac}:
    $ref: paths/api_gateway_by_mac.yaml
  /api/gateway/by_pairing_id/{gateway_pairing_id}:
    $ref: paths/api_gateway_by_pairing_id.yaml
  /api/gateway/user:
    $ref: paths/api_gateway_user.yaml
  /api/gateway/by_id/{gateway_id}:
    $ref: paths/api_gateway_by_id.yaml
  /api/gateway/key:
    post:
      $ref: paths/api_gateway_key_post.yaml
    delete:
      $ref: paths/api_gateway_key_delete.yaml
  /api/gateway/schedule_key:
    $ref: paths/api_gateway_schedule_key.yaml
  /api/gateway/other_key:
    $ref: paths/api_gateway_other_key.yaml
  /api/gateway/schedule_other_key:
    $ref: paths/api_gateway_schedule_other_key.yaml
  /api/gateway/pair:
    $ref: paths/api_gateway_pair.yaml
  /api/gateway/unpair:
    $ref: paths/api_gateway_unpair.yaml
  /api/gateway/sync:
    $ref: paths/api_gateway_sync.yaml
  /api/gateway/open:
    $ref: paths/api_gateway_open.yaml
  /api/gateway/close:
    $ref: paths/api_gateway_close.yaml











